apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkc-tools
spec:
  distribution:
    version: v1.18
  topology:
    controlPlane:
      class: best-effort-small
      count: 1
      storageClass: kubernetes-gold-storage-policy
    workers:
      class: best-effort-small
      count: 3
      storageClass: kubernetes-gold-storage-policy
      
